function Workflow() {
    const steps = [
        {
            number: 1,
            title: 'Define Requirements',
            description: 'Describe your project idea. The Requirements Agent will help you create comprehensive documentation.'
        },
        {
            number: 2,
            title: 'Design Architecture',
            description: 'Review and refine system designs, database schemas, and UI mockups generated by the Design Agent.'
        },
        {
            number: 3,
            title: 'Generate Code',
            description: 'The Development Agent creates clean, production-ready code following industry best practices.'
        },
        {
            number: 4,
            title: 'Test & Validate',
            description: 'Automated testing ensures quality and coverage. Review test results and fix issues.'
        }
    ]

    return (
        <section className="workflow" id="workflow">
            <div className="container">
                <div className="section-header">
                    <h2 className="section-title">How It Works</h2>
                    <p className="section-subtitle">From idea to testing in simple steps</p>
                </div>
                <div className="workflow-timeline">
                    {steps.map((step, index) => (
                        <div key={index} className="timeline-item">
                            <div className="timeline-marker">{step.number}</div>
                            <div className="timeline-content">
                                <h3>{step.title}</h3>
                                <p>{step.description}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    )
}

export default Workflow
